"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
palette = "cyber"

format = """
[ $username ](fg:green bg:color_slateblue)\
[](fg:color_slateblue bg:color_slate)\
$directory\
[](fg:color_slate bg:color_bluegray)\
$rust\
$python\
[](fg:color_bluegray bg:color_navy)\
$git_branch\
$git_commit\
$git_state\
$git_status\
[](fg:color_navy bg:color_darknavy)\
[](fg:color_darknavy)\
$cmd_duration\
$fill\
[](fg:color_darknavy)\
[](fg:color_slateblue bg:color_darknavy)\
[$time ](fg:#FFD75F bg:color_slateblue)\
$line_break\
$character"""

[palettes.cyber]
color_slateblue = "#2a2f3a"
color_slate = "#303746"
color_bluegray = "#3a4356"
color_navy = "#26324a"
color_darknavy = "#1f2633"

color_fg0 = "#e6e6e6"
color_bg1 = "#121212"
color_green = "#39FF14"
color_red = "#ff4628"
color_orange = "#ff9f1c"
color_brightyellow = "#FFD75F"
color_brightblack = "#7f8ea3"
color_arch = "#1793d1"
color_cyan = "#00d2ff"
color_brightblue = "#5FAFFF"

[fill]
symbol = " "

[username]
show_always = true
style_user = "fg:color_green bg:color_slateblue"
style_root = "fg:color_red bg:color_slateblue"
format = "$user"
disabled = false

[directory]
style = "fg:color_brightblue bg:color_slate"
read_only_style = "bg:color_slate fg:color_orange"
read_only = "󰌾 "
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 2
truncation_symbol = "…/"


[git_branch]
disabled = false
only_attached = true
symbol = ""
style = "bg:color_navy fg:color_orange"
format = '[ $symbol $branch ]($style)'

[git_commit]
disabled = false
tag_disabled = false
tag_symbol = " 󰓼 "
style = "bg:color_navy fg:color_orange"
format = '[ $hash$tag ]($style)'

[git_state]
disabled = false
style = "bold bg:color_navy fg:color_brightyellow"
format = '[ $state $progress_current/$progress_total ]($style)'

[git_status]
disabled = false
style = "bold bg:color_navy fg:color_orange"
format = '[ $all_status$ahead_behind ]($style)'

[rust]
disabled = false
symbol = ""
style = "bg:color_bluegray fg:color_fg0"
format = '[ $symbol ]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "fg:#FFD75F bg:color_slateblue"
format = "[  $time]($style)"

[python]
disabled = false
symbol = ""
style = "bg:color_bluegray fg:color_brightyellow"
format = '[ $symbol $virtualenv ]($style)'

[cmd_duration]
disabled = false
style = "fg:color_brightblack"
min_time = 5000
format = '[  $duration ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[❯](bold fg:color_green)"
error_symbol   = "[❯](bold fg:color_red)"
